### ISSUE TITLE
Find Common Characters

### ISSUE THREAD

**Issue by h2jeong** [wallypark710/Q-A#2]
글 올리는 양식을 못 지켰더라도 용서해주세요. ㅜㅜ

**URL** 
https://leetcode.com/problems/find-common-characters/

**질문**
리트코드 문제입니다. 우선은 아래 제 코드로 나오는 값은 
["e"] 으로 "e"는 3번, "l"은 6번이 나옵니다. 
3번 중복된 character를 찾아내는 것으로, 문제에서 원하는 답은 중복된 스펠링도 각각의 값으로 나와야 해서 
["e","l","l"] 입니다.

올바른 접근인지도 잘 모르겠고 어떻게 해야 같은 character를 다른 키로 저장할 수 있는지 답답해서요.

**문제** 
Given an array A of strings made only from lowercase letters, return a list of all characters that show up in all strings within the list (including duplicates).  For example, if a character occurs 3 times in all strings but not 4 times, you need to include that character three times in the final answer.

You may return the answer in any order.

**Example 1**

Input: ["bella","label","roller"]
Output: ["e","l","l"]

-----------------------------------------------
**제 코드** 

var commonChars = function(A) {
    const result = [];

    let firstObj = [...A[0]].reduce((acc, curr) => {
        acc[curr] = 1;
        return acc;
    } , {});
    
    let restObj = A.slice(1)
      .map(x => [...x])
      .reduce((acc, curr) => {
        acc = firstObj;

        curr.forEach(function (y) {
            if (y in acc) acc[y]++;
        })
        return acc;
    }, {});
    
    for (let key in restObj) {
        if (restObj[key] === 3) result.push(key);
    }
    return result;
}

**Comment by wallypark710** [comment]
주어진 단어 리스트에 모두 포함된 스펠링을 배열에 담아 반환하는 문제군요. 단 하나의 스펠링은 한 단어에서 한번만 체크해야 할것 같아요. 예를 들어 ["app", "pain", "pad"] 의 결과는 [a, p] 가 나와야겠죠. [a, p, p] 가 아니라요

같은 character를 다른 키로 저장하시는 방법보다, character의 갯수를 카운트 해보시면 어떨까요?
예를들면
```
"bella" 의 경우
{
    a : 1,
    b : 1,
    e : 1,
    l : 2
} 
```
각각의 객체에 키가 있는지, 있다면 카운트가 몇개인지를 비교해보시면 좋을거가타요. 그리고 카운트하신건 카운트를 하나 감소시켜주면 되겠죠?

한번만더 시도해보시고 다시 댓글 남겨주세요 :)

**Comment by h2jeong** [comment]
예제를 보면 

Input: ["bella","label","roller"]
Output: ["e","l","l"]

이런 식으로 한 단어의 모든 스펠링을 각각 체크하는 문제입니다. ㅜㅜ

**Comment by wallypark710** [comment]
세 단어에 모두 들어가있는 스펠링을 찾아서 반환하는 문제 아닌가요?

**Comment by h2jeong** [comment]
네. 맞습니당. ㅜㅜ
